---
sudo: false

language: perl

perl:
  - blead
  - dev
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'

cache:
  directories:
    - $HOME/perl5

matrix:
  allow_failures:
    - perl: blead
  include:
    - env: COVERAGE="codecov coveralls"
      perl: '5.26'
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -lv $(test-dirs)

after_success:
  - coverage-report

### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
